version: '3'
services:
  database:
    image: "postgres:12.6"
    environment:
      - POSTGRES_DB=avenger
      - POSTGRES_USER=avenger
      - POSTGRES_PASSWORD=avenger
    ports:
      - "5432:5432"